remote_theme: just-the-docs/just-the-docs
search_enabled: true
heading_anchors: true

title: Zotero 介紹
description: 一份關於 Zotero 的開源使用教學，採用 GPLv3 授權。

aux_links:
  "在 GitHub 上查看":
    - https://github.com/Arc13Tangent/Intro-to-Zotero

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 2..3
